import type { Product } from '@/types'

export const stakingProducts: Product[] = [
  {
    id: 'lido-steth-1',
    name: 'Lido stETH Stake',
    description: 'Stake ETH with Lido and receive stETH liquid staking token. Earn ~3.2% APY with instant liquidity.',
    price: 0.00001,
    priceUSD: 3350,
    image: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    category: 'staking',
    chain: 'ethereum',
    apy: 3.2,
    tvl: 28000000000,
    token: 'stETH',
    protocol: 'Lido',
    inStock: true,
    maxQuantity: 100,
  },
  {
    id: 'rocketpool-reth-1',
    name: 'Rocket Pool rETH',
    description: 'Decentralized Ethereum staking with rETH. Earn ~3.1% APY with minimal requirements.',
    price: 0.000012,
    priceUSD: 4000,
    image: 'https://cryptologos.cc/logos/rocket-pool-rpl-logo.png',
    category: 'staking',
    chain: 'ethereum',
    apy: 3.1,
    tvl: 450000000,
    token: 'rETH',
    protocol: 'Rocket Pool',
    inStock: true,
    maxQuantity: 50,
  },
  {
    id: 'gmx-glp-1',
    name: 'GMX GLP Pool',
    description: 'Provide liquidity to GMX and earn ~18.5% APY in ETH and GMX rewards.',
    price: 1.05,
    priceUSD: 1000,
    image: 'https://cryptologos.cc/logos/gmx-gmx-logo.png',
    category: 'lp',
    chain: 'arbitrum',
    apy: 18.5,
    tvl: 580000000,
    token: 'GLP',
    protocol: 'GMX',
    inStock: true,
    maxQuantity: 200,
  },
  {
    id: 'pancakeswap-cake-1',
    name: 'PancakeSwap CAKE Syrup',
    description: 'Stake CAKE in Syrup Pool and earn ~8.5% APY with flexible staking.',
    price: 10,
    priceUSD: 25,
    image: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.png',
    category: 'staking',
    chain: 'bsc',
    apy: 8.5,
    tvl: 420000000,
    token: 'CAKE',
    protocol: 'PancakeSwap',
    inStock: true,
    maxQuantity: 500,
  },
  {
    id: 'aave-aeth-1',
    name: 'Aave ETH Lending',
    description: 'Supply ETH to Aave V3 and earn ~2.8% APY with instant withdrawal.',
    price: 0.008,
    priceUSD: 3000,
    image: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    category: 'lending',
    chain: 'ethereum',
    apy: 2.8,
    tvl: 12000000000,
    token: 'aETH',
    protocol: 'Aave',
    inStock: true,
    maxQuantity: 100,
  },
  {
    id: 'velodrome-velo-1',
    name: 'Velodrome VELO LP',
    description: 'Provide liquidity on Velodrome and earn ~22.5% APY in VELO rewards.',
    price: 50,
    priceUSD: 100,
    image: 'https://cryptologos.cc/logos/velodrome-finance-velo-logo.png',
    category: 'lp',
    chain: 'optimism',
    apy: 22.5,
    tvl: 180000000,
    token: 'VELO',
    protocol: 'Velodrome',
    inStock: true,
    maxQuantity: 300,
  },
  {
    id: 'eigenlayer-ezeth-1',
    name: 'EigenLayer Restaking',
    description: 'Restake your staked ETH and earn additional ~4.5% APY in rewards.',
    price: 0.009,
    priceUSD: 3500,
    image: 'https://avatars.githubusercontent.com/u/111273511',
    category: 'staking',
    chain: 'ethereum',
    apy: 4.5,
    tvl: 8500000000,
    token: 'ezETH',
    protocol: 'EigenLayer',
    inStock: true,
    maxQuantity: 80,
  },
  {
    id: 'aerodrome-aero-1',
    name: 'Aerodrome AERO LP',
    description: 'Provide liquidity on Aerodrome and earn ~28.5% APY in AERO tokens.',
    price: 25,
    priceUSD: 50,
    image: 'https://avatars.githubusercontent.com/u/110723342',
    category: 'lp',
    chain: 'base',
    apy: 28.5,
    tvl: 380000000,
    token: 'AERO',
    protocol: 'Aerodrome',
    inStock: true,
    maxQuantity: 400,
  },
  {
    id: 'traderjoe-joe-1',
    name: 'Trader Joe LP',
    description: 'Stake LP tokens on Trader Joe and earn ~14.8% APY in JOE rewards.',
    price: 100,
    priceUSD: 80,
    image: 'https://cryptologos.cc/logos/trader-joe-joe-logo.png',
    category: 'lp',
    chain: 'avalanche',
    apy: 14.8,
    tvl: 320000000,
    token: 'JOE',
    protocol: 'Trader Joe',
    inStock: true,
    maxQuantity: 250,
  },
  {
    id: 'polygon-staking-1',
    name: 'Polygon Native Staking',
    description: 'Stake MATIC directly on Polygon and earn ~4.2% APY with native rewards.',
    price: 1000,
    priceUSD: 400,
    image: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
    category: 'staking',
    chain: 'polygon',
    apy: 4.2,
    tvl: 4200000000,
    token: 'MATIC',
    protocol: 'Polygon',
    inStock: true,
    maxQuantity: 1000,
  },
  {
    id: 'venus-bnb-1',
    name: 'Venus BNB Lending',
    description: 'Supply BNB to Venus and earn ~2.8% APY with borrow capabilities.',
    price: 0.3,
    priceUSD: 180,
    image: 'https://cryptologos.cc/logos/venus-xvs-logo.png',
    category: 'lending',
    chain: 'bsc',
    apy: 2.8,
    tvl: 750000000,
    token: 'vBNB',
    protocol: 'Venus',
    inStock: true,
    maxQuantity: 150,
  },
  {
    id: 'boost-yield-1',
    name: 'Yield Boost Package',
    description: 'Premium yield optimization across multiple protocols. Automated rebalancing for max returns.',
    price: 100,
    priceUSD: 100,
    image: 'https://via.placeholder.com/48/22c55e/ffffff?text=BOOST',
    category: 'boost',
    chain: 'multi',
    apy: 35.0,
    tvl: 50000000,
    token: 'BOOST',
    protocol: 'Staked.me',
    inStock: true,
    maxQuantity: 10,
  },
]

export function getProductsByCategory(category: Product['category']): Product[] {
  return stakingProducts.filter((p) => p.category === category)
}

export function getProductsByChain(chain: string): Product[] {
  return stakingProducts.filter((p) => p.chain === chain)
}

export function getProductById(id: string): Product | undefined {
  return stakingProducts.find((p) => p.id === id)
}
